### ISSUE TITLE
Facial details estimation

### ISSUE THREAD

**Issue by ShengliL** [apchenstu/Facial_Details_Synthesis#10]
Appreciate for your project!
I try to use "Released version" to reconstruct face with details. I followed the guidance and ran the code `python facialDetails.py -i ./samples/details/019615.jpg -o ./results` liked the example did. Everythings seemed to go right except 
`LOG (WARN: Material file [ result.mtl ] not found.
WARN: Failed to load material file(s). Use default material.` returned. 
However, I still got  a reconstructed face showed in a render window. But the resonstructed face had no details such as forehead.
When I ran the code `python facialDetails.py -i ./samples/details -o ./results` ,the returned logs are as follow:
![捕获](https://user-images.githubusercontent.com/30545630/64341929-07cc4500-d01c-11e9-893c-4271727f036c.PNG)

I wonder whether I got something wrong or for some reasons such as privacy or commercial reasons, this released version can't reconstruct a face with details. I want to compare our project with the state of the art work,  I hope to get your answer.

**Comment by apchenstu** [comment]
Sorry about the mess file versions. Could you show me the output files, it's hard figure out what's wrong with it. 
correct output should looks like as below, I think you may using an old version released package(updated this morning), you can try the newest package.
![image](https://user-images.githubusercontent.com/16453770/64351383-cb551500-d02c-11e9-87f5-429a67bfa381.png)

**Comment by ShengliL** [comment]
Thank you for your reply. I update the new version and output seem to be right.

![捕获1](https://user-images.githubusercontent.com/30545630/64397306-697bc600-d093-11e9-9724-3b2f9480a7bf.PNG)

I will close this issue.

**Comment by hariskhan101** [comment]
Hey, Hope you are doing good.
I am having a issue in .mtl file and my result.isomap.png is showing just black screen.

 What could be the issue.

This is the warning I am getting.

LOG (WARN: Material file [ result.mtl ] not found.
WARN: Failed to load material file(s). Use default material.
)
~In file (e:\face2face\code\release_v1\src\face_rendering\src\includes\ind\loaders.cc) , line (81)
