### ISSUE TITLE
CUDA out of  memory

### ISSUE THREAD

**Issue by Ivy147** [apchenstu/Facial_Details_Synthesis#13]
Hi,anpei.
I ran " python facialDetails.py -i ./samples/details/019615.jpg -o ./results --emotion 1"
the error came out:CUDA out of  memory
My gpu card is GTX 1080 8G,How many memory do you need?
Can  I set any  parameters like batch size to reduce memory?

**Comment by apchenstu** [comment]
for batch size config, you can use `--batchSize XX`, by default, it is 100.

for more configuration, please reference to [opions](https://github.com/apchenstu/Facial_Details_Synthesis/tree/master/src/DFDN/options)
