### ISSUE TITLE
Read Morphable Model ERROR.

### ISSUE THREAD

**Issue by gyh2556406** [apchenstu/Facial_Details_Synthesis#14]
I create bfm2017-1_bfm_nomouth.bin by running: python convert-bfm2017-to-eos.py successfully, while it then fails when running:
python .\proxyPredictor.py -i .\samples\proxy\000001.jpg -o .\results\

error message:
[Error loading the Morphable Model: Failed to read 16 bytes from input stream! Read 9]

Quite appreciate for any possible helps!

**Comment by apchenstu** [comment]
Please reference to [here](https://github.com/apchenstu/Facial_Details_Synthesis/issues/5#issuecomment-528735705)
