### ISSUE TITLE
The output of textureRender.exe is missing

### ISSUE THREAD

**Issue by richard-bmc** [apchenstu/Facial_Details_Synthesis#19]
Thanks for sharing the code, but I cannot get the result from the textureRender. The following image is the result I got after executing proxyPredictor.py, but result.isomap.png is missing: 
 
![image](https://user-images.githubusercontent.com/6274803/69226480-2e316380-0bbb-11ea-9d63-1546aa93cc9b.png)

I also copied "glew32.dll" and "opencv_world_330.dll" to the folder where textureRender resides in, but I still cannot get the result.
I tested the code in anaconda environment, and the versions of dependent packages are as follows: 
Python 3.6.9
eos-py 0.16.1
torch 1.3.1
torchvision 0.2.2
tensorflow-gpu 2.0.0
And my graphics card is RTX 2080. My operating system is Windows 10.

Any help will be appreciated. Thanks in advance!

**Comment by richard-bmc** [comment]
This issue was caused by [glfw and remote desktop connection](https://github.com/glfw/glfw/issues/1245).
If I ran textureRender directly (not via remote desktop), it will generate the correct result.

**Comment by XIAO-RUI-RUI** [comment]
Try to check out the related *.exe(e.g. textureRender.exe) in python scripts.
