### ISSUE TITLE
error with pip install eos-py==0.16.1 

### ISSUE THREAD

**Issue by wtrnash** [apchenstu/Facial_Details_Synthesis#27]
作者您好，非常感谢您的分享。我的系统是win10，由于您的代码需要0.16.1版本的eos-py，而我pip该版本以及该版本之前的eos-py都会报错，如下：
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1
而0.16.1版本之后的eos-py我都可以通过pip成功安装，但是这样就会遇到#14的问题，有什么办法解决吗

**Comment by LansburyCH** [comment]
Is your python 3.x? Can you create an empty virtual python environment and try installing again to see if the problem still exists?

**Comment by wtrnash** [comment]
> Is your python 3.x? Can you create an empty virtual python environment and try installing again to see if the problem still exists?

Thanks! I create an empty virtual python environment and solve this problem.

**Comment by shash29-dev** [comment]
Error is still there with new environment.

        ```CMake Error at CMakeLists.txt:5 (project):
        Generator

          Visual Studio 15 2017 Win64

        could not find any instance of Visual Studio.```

I have vs19 installed. Is 15 a requirement?

**Comment by Yuqian-He** [comment]
> Error is still there with new environment.
> 
> ```
>     ```CMake Error at CMakeLists.txt:5 (project):
>     Generator
> 
>       Visual Studio 15 2017 Win64
> 
>     could not find any instance of Visual Studio.```
> ```
> 
> I have vs19 installed. Is 15 a requirement?

Did you figure it out? I had the same error with pip install eos-py==0.16.1
