### ISSUE TITLE
Question about generate proxy?

### ISSUE THREAD

**Issue by xinghuokang** [apchenstu/Facial_Details_Synthesis#29]
(Pytorch) D:\FacialDetailsSynthesis\released_v0.1>python proxyPredictor.py -i ./samples/proxy -o ./results
Attempting to read from directory: D:\FacialDetailsSynthesis\released_v0.1\samples\proxy
Loading the model
Model loaded
Starting tracking
D:\FacialDetailsSynthesis\released_v0.1\samples\proxy\000001.jpg
D:\FacialDetailsSynthesis\released_v0.1\samples\proxy\000005.jpg
D:\FacialDetailsSynthesis\released_v0.1\samples\proxy\000007.jpg
D:\FacialDetailsSynthesis\released_v0.1\samples\proxy\000008.jpg
D:\FacialDetailsSynthesis\released_v0.1\samples\proxy\000011.jpg
===> Landmarks detection done.

**===> estimating proxy of D:\FacialDetailsSynthesis\released_v0.1\samples\proxy\000001.jpg
Error loading the Morphable Model: Failed to read 16 bytes from input stream! Read 9
===> estimating proxy of D:\FacialDetailsSynthesis\released_v0.1\samples\proxy\000005.jpg
Error loading the Morphable Model: Failed to read 16 bytes from input stream! Read 9
===> estimating proxy of D:\FacialDetailsSynthesis\released_v0.1\samples\proxy\000007.jpg
Error loading the Morphable Model: Failed to read 16 bytes from input stream! Read 9
===> estimating proxy of D:\FacialDetailsSynthesis\released_v0.1\samples\proxy\000008.jpg
Error loading the Morphable Model: Failed to read 16 bytes from input stream! Read 9
===> estimating proxy of D:\FacialDetailsSynthesis\released_v0.1\samples\proxy\000011.jpg
Error loading the Morphable Model: Failed to read 16 bytes from input stream! Read 9**

Hi, apchenstu:
      what's the problem? I can't know how to solve it.
Look forward your reply!

**Comment by xinghuokang** [comment]
Hi, 
I follow your instructions, all success except pip install eos-py, I can not install 0.16.1, so I pip install eos-py=1.1.2

**Comment by LansburyCH** [comment]
The problem is due to the version of eos-py. What is your error message when installing eos-py 0.16.1?

**Comment by xinghuokang** [comment]
Hi，LansburyCH 
Thank you for your reply, when I install eos-py==0.16.1, it occurs errors caused by VS(I used vs2015). Then I reinstall VS2017, it dose not occurs any errors.
