### ISSUE TITLE
LOG (Cannot open file [D:\Folder_1\init_facial_fidelity_capture\results\019615\result.obj] )

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [apchenstu/Facial_Details_Synthesis#44]
When I am executing the following command in the PyCharm terminal
```
python facialDetails.py -i ./samples/details/019615.jpg -o ./results
```

then in the output, I am getting the following error:

Load preTrain model done.
Load preTrain model done.
Loading the model
Model loaded
Starting tracking
D:\PycharmProjects\init_facial_fidelity_capture\samples\details\019615.jpg
===> Landmarks detection done.

===> estimating proxy of D:\PycharmProjects\init_facial_fidelity_capture\samples\details\019615.jpg
Using expression piror from Facial Action Coding features.
Error loading the Morphable Model: Failed to read 16 bytes from input stream! Read 9
===> predicting details of D:\PycharmProjects\init_facial_fidelity_capture\samples\details\019615.jpg

**LOG (Cannot open file [D:\PycharmProjects\init_facial_fidelity_capture\results\019615\result.obj])**
**~In file (e:\face2face\code\release_v1\src\face_rendering\src\includes\ind\loaders.cc) , line (81)**
**ERROR ()**
**~In file (e:\face2face\code\release_v1\src\face_rendering\src\includes\ind\loaders.cc) , line (83)**

Please help me in solving this.

**Comment by apchenstu** [comment]
Please refe to [here](https://github.com/apchenstu/Facial_Details_Synthesis/issues/5#issuecomment-528735705), thanks~
