### ISSUE TITLE
fit-model.exe error

### ISSUE THREAD

**Issue by andorxornot** [apchenstu/Facial_Details_Synthesis#5]
it needs jpeg.dll, glew32.dll, msvcr90.dll, msvcp90.dll, tiff.dll, cudart64_100.dll
It crashes at the start, then after I copy them from the internet

could you put your copies of dlls in a release?

**Comment by apchenstu** [comment]
Thank you! I add some dlls to the new release package. : )

**Comment by Ivy147** [comment]
I find missing lzma.dll when running fit-model.exe，can you put your dll here?

**Comment by apchenstu** [comment]
sorry, here you are!
[lzma.zip](https://github.com/apchenstu/Facial_Details_Synthesis/files/3573466/lzma.zip)

**Comment by Ivy147** [comment]
> sorry, here you are!
> [lzma.zip](https://github.com/apchenstu/Facial_Details_Synthesis/files/3573466/lzma.zip)

Thank you so much!
But there still have some of the problems:
>python proxyPredictor.py -i ./samples/proxy/000001.jpg -o ./results
Loading the model
Model loaded
Starting tracking
E:\program\3D_Face_Reconstruction\V2.0\code\Facial_Details_Synthesis\released_v0
.1\samples\proxy\000001.jpg
===> Landmarks detection done.

===> estimating proxy of E:\program\3D_Face_Reconstruction\V2.0\code\Facial_Deta
ils_Synthesis\released_v0.1\samples\proxy\000001.jpg
Error loading the Morphable Model: Failed to read 16 bytes from input stream! Re
ad 9
Can you give me some advices to solve this problem?

**Comment by apchenstu** [comment]
This error may caused by you are using a newest version of eos-py package.
You may need to follow the guidance: `pip install --force-reinstall eos-py==0.16.1` and then regenerate bfm2017

**Comment by Ivy147** [comment]
> This error may caused by you are using a newest version of eos-py package.
> You may need to follow the guidance: `pip install --force-reinstall eos-py==0.16.1` and then regenerate bfm2017

Yes,and I change to eos-py==0.16.1 ,it works!  Thank you!
By the way,I can't install eos-py==0.16.1 with python 3.7 sucessfully,at last, I install it with python 3.6.

**Comment by craftsliu** [comment]
> > This error may caused by you are using a newest version of eos-py package.
> > You may need to follow the guidance: `pip install --force-reinstall eos-py==0.16.1` and then regenerate bfm2017
> 
> Yes,and I change to eos-py==0.16.1 ,it works! Thank you!
> By the way,I can't install eos-py==0.16.1 with python 3.7 sucessfully,at last, I install it with python 3.6.

yes，it can't install eos-py==0.16.1 with python 3.7 ,all can't support build through whl file。it need python=3.6.when I create a new python=3.6 enviroment,I can success install eos-py==0.16.1
