### ISSUE TITLE
 DFDN checkpoints can not be download

### ISSUE THREAD

**Issue by xinedison** [apchenstu/Facial_Details_Synthesis#6]
Thank you for sharing your code. When I want to download the DFDN checkpoint fron one drive, I get message that says it is not available. I wonder is the address for DFDN model be updated?

**Comment by apchenstu** [comment]
Hey there, thanks for your reminder, the previous link already expired, the links already up to date, please try again.

**Comment by xinedison** [comment]
The updated link works. Thank you.
