### ISSUE TITLE
cpu supports?

### ISSUE THREAD

**Issue by HaiyongJiang** [apchenstu/Facial_Details_Synthesis#9]
Dear authors, thank you for your great work. I would like to try the code on my computer. However, I am not sure if the code could be run in the cpu mode. Thank you.

**Comment by apchenstu** [comment]
For this released version, proxy estimation procession only CPU, but details prediction needs GPU. Thanks.

**Comment by HaiyongJiang** [comment]
Hi @apchenstu, thank you for your reply. Another question is that if details prediction module relies on Windows-specific programs?

**Comment by apchenstu** [comment]
Yeah, the proxy estimator is suggested compiling on window os, as we it is a visual studio project.   
BTW, I think it's not difficult to let the code support cpu, just need to modify  some tensor type I think.

**Comment by HaiyongJiang** [comment]
Thanks. I will try that.
